/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.outfitme.outfitme;

import com.outfitme.dao.ThongKeDAO;
import com.outfitme.utils.Auth;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ThongKeJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ThongKe
     */
    public ThongKeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsThongKe = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblNam = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        lblSoHD = new javax.swing.JLabel();
        lblSoDoanhThu = new javax.swing.JLabel();
        lblTogNam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMaSP = new javax.swing.JLabel();
        btnFindSL = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSLSP = new javax.swing.JTable();
        txtMaSP = new javax.swing.JTextField();
        cboSLSP = new javax.swing.JComboBox<>();
        lblMaNV4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDHNV2 = new javax.swing.JTable();
        txtMaNV2 = new javax.swing.JTextField();
        lblMaNV2 = new javax.swing.JLabel();
        btnLoad_DHNV1 = new javax.swing.JButton();
        lblMaNV3 = new javax.swing.JLabel();
        cboDH = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblNam2 = new javax.swing.JLabel();
        cboThang = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDoanhThuThang = new javax.swing.JTable();
        lblThangDT = new javax.swing.JLabel();
        lblTogThang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNam.setText("Năm:");

        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số hóa đơn", "Doanh thu", "Thấp nhất", "Cao nhất", "Trung bình"
            }
        ));
        jScrollPane1.setViewportView(tblDoanhThu);

        lblSoHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoHD.setForeground(new java.awt.Color(255, 0, 51));
        lblSoHD.setText("Tổng doanh thu tới hiện nay là");

        lblSoDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoDoanhThu.setForeground(new java.awt.Color(255, 0, 0));
        lblSoDoanhThu.setText("0 đ");

        lblTogNam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTogNam.setForeground(new java.awt.Color(255, 0, 51));
        lblTogNam.setText("Tổng Năm :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSoDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSoHD, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addGap(412, 412, 412))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblNam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboNam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTogNam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNam)
                    .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTogNam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblSoHD)
                .addGap(18, 18, 18)
                .addComponent(lblSoDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        tabsThongKe.addTab("Doanh Thu", jPanel1);

        lblMaSP.setText("Mã sản phẩm:");

        btnFindSL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/outfitme/icon/research.png"))); // NOI18N
        btnFindSL.setText("Find");
        btnFindSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindSLActionPerformed(evt);
            }
        });

        tblSLSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng tồn kho", "Số lượng đã bán"
            }
        ));
        jScrollPane2.setViewportView(tblSLSP);

        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        cboSLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSLSPActionPerformed(evt);
            }
        });

        lblMaNV4.setText("Năm:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMaNV4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboSLSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaSP)
                                .addGap(18, 18, 18)
                                .addComponent(btnFindSL)))))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSP)
                    .addComponent(btnFindSL)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV4)
                    .addComponent(cboSLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabsThongKe.addTab("Số lượng sản phẩm", jPanel2);

        tblDHNV2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Tổng hóa đơn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblDHNV2);

        lblMaNV2.setText("Mã nhân viên:");

        btnLoad_DHNV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/outfitme/icon/Refresh.png"))); // NOI18N
        btnLoad_DHNV1.setText("Load");
        btnLoad_DHNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoad_DHNV1ActionPerformed(evt);
            }
        });

        lblMaNV3.setText("Năm:");

        cboDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblMaNV3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboDH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblMaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaNV2)
                                .addGap(18, 18, 18)
                                .addComponent(btnLoad_DHNV1)))))
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV2)
                    .addComponent(btnLoad_DHNV1)
                    .addComponent(txtMaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV3)
                    .addComponent(cboDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabsThongKe.addTab("Đơn hàng của nhân viên", jPanel4);

        lblNam2.setText("Tháng");

        tblDoanhThuThang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tổng giao dịch", "Doanh thu", "Thấp nhất", "Cao nhất", "Trung bình"
            }
        ));
        jScrollPane3.setViewportView(tblDoanhThuThang);

        lblThangDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThangDT.setForeground(new java.awt.Color(153, 0, 153));
        lblThangDT.setText("Tổng doanh thu của tháng 1:");

        lblTogThang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTogThang.setForeground(new java.awt.Color(255, 0, 0));
        lblTogThang.setText("0 đ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblNam2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboThang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThangDT, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTogThang, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNam2)
                    .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThangDT)
                    .addComponent(lblTogThang))
                .addGap(60, 60, 60))
        );

        tabsThongKe.addTab("Doanh Thu Tháng", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabsThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(tabsThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindSLActionPerformed
        // TODO add your handling code here:
        fillTableSLSP();
    }//GEN-LAST:event_btnFindSLActionPerformed

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void cboSLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSLSPActionPerformed

    private void btnLoad_DHNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoad_DHNV1ActionPerformed
        // TODO add your handling code here:
        fillTableDHNV2();
    }//GEN-LAST:event_btnLoad_DHNV1ActionPerformed

    private void cboDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDHActionPerformed
        // TODO add your handling code here:
        fillTableDHNV2();
    }//GEN-LAST:event_cboDHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThongKeJDialog dialog = new ThongKeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindSL;
    private javax.swing.JButton btnLoad_DHNV1;
    private javax.swing.JComboBox<String> cboDH;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboSLSP;
    private javax.swing.JComboBox<String> cboThang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblMaNV2;
    private javax.swing.JLabel lblMaNV3;
    private javax.swing.JLabel lblMaNV4;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblNam2;
    private javax.swing.JLabel lblSoDoanhThu;
    private javax.swing.JLabel lblSoHD;
    private javax.swing.JLabel lblThangDT;
    private javax.swing.JLabel lblTogNam;
    private javax.swing.JLabel lblTogThang;
    private javax.swing.JTabbedPane tabsThongKe;
    private javax.swing.JTable tblDHNV2;
    private javax.swing.JTable tblDoanhThu;
    private javax.swing.JTable tblDoanhThuThang;
    private javax.swing.JTable tblSLSP;
    private javax.swing.JTextField txtMaNV2;
    private javax.swing.JTextField txtMaSP;
    // End of variables declaration//GEN-END:variables
   ThongKeDAO dao = new ThongKeDAO();

    public void selectTab(int index) {
        tabsThongKe.setSelectedIndex(index);
    }

    void init() {
        setLocationRelativeTo(null);

        fillComboBoxNam();
        fillComboBoxNamDH();
        fillComboBoxNamSLSP();
        fillComboBoxDoanhThuThang();

        fillTableDoanhThu();
        fillTableDHNV2();
        fillTableSLSP();
        fillTableDoanhThuThang();

        this.selectTab(0);
    }

    void fillComboBoxNam() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboNam.getModel();
        model.removeAllElements();

        List<Integer> list = dao.selectYears();
        for (Integer year : list) {
            model.addElement(year);
        }

        if (model.getSize() > 0) {
            cboNam.setSelectedIndex(0);
        }
    }

    void fillComboBoxNamDH() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDH.getModel();
        model.removeAllElements();

        List<Integer> list = dao.selectYears();
        for (Integer year : list) {
            model.addElement(year);
        }

        if (model.getSize() > 0) {
            cboDH.setSelectedIndex(0);
        }
    }

    void fillComboBoxNamSLSP() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboSLSP.getModel();
        model.removeAllElements();

        List<Integer> list = dao.selectYears();
        for (Integer year : list) {
            model.addElement(year);
        }

        if (model.getSize() > 0) {
            cboSLSP.setSelectedIndex(0);
        }
    }

    void fillComboBoxDoanhThuThang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboThang.getModel();
        model.removeAllElements();

        List<Integer> list = dao.selectMonth();
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu tháng nào trong cơ sở dữ liệu!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            for (Integer month : list) {
                model.addElement(month);
            }
            cboThang.setSelectedIndex(0);
        }
    }

    void fillTableDoanhThu() {
        Object selected = cboNam.getSelectedItem();
        if (selected == null) {
            return;
        }

        // Lấy tổng số hóa đơn và doanh thu từ đầu đến nay
        Object[] kq = dao.selectDoanhThu();
        lblSoHD.setText("Tổng số hóa đơn tới hiện nay: " + kq[0]);
        lblSoDoanhThu.setText("Tổng số doanh thu tới hiện nay: " + String.format("%,.0f", (Double) kq[1]) + " VND");

        int nam = (Integer) selected;
        lblTogNam.setText("Tổng doanh thu của năm " + nam + ":");

        DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();
        model.setRowCount(0);

        // Lấy dữ liệu doanh thu theo năm từ lịch sử mua hàng
        List<Object[]> list = dao.getDoanhThuTheoNam(nam);
        for (Object[] row : list) {
            model.addRow(new Object[]{
                row[0], // Tổng giao dịch
                String.format("%,.0f", (Double) row[1]), // Tổng doanh thu
                String.format("%,.0f", (Double) row[2]), // Thấp nhất
                String.format("%,.0f", (Double) row[3]), // Cao nhất
                String.format("%,.0f", (Double) row[4]) // Trung bình
            });
        }

        // Cập nhật nhãn tổng doanh thu của năm
        if (tblDoanhThu.getRowCount() > 0) {
            double togDt = Double.parseDouble(tblDoanhThu.getValueAt(0, 1).toString().replace(",", ""));
            lblTogNam.setText("Tổng doanh thu của năm " + nam + ": " + String.format("%,.0f", togDt) + " VND");
        } else {
            lblTogNam.setText("Tổng doanh thu của năm " + nam + ": 0 VND");
        }
    }

    public void fillTableSLSP() {
        Object selected = cboSLSP.getSelectedItem();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một năm để thống kê!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblSLSP.getModel();
        model.setRowCount(0);

        String maSP = txtMaSP.getText().trim();
        int year = (Integer) selected;

        try {
            List<Object[]> list = dao.getSLSP(maSP, year);
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Không tìm thấy dữ liệu cho " + (maSP.isEmpty() ? "bất kỳ sản phẩm nào" : "sản phẩm '" + maSP + "'")
                        + " trong năm " + year + "!",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (Object[] row : list) {
                    model.addRow(new Object[]{
                        row[0],
                        row[1],
                        row[2],
                        row[3]
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Lỗi khi tải dữ liệu số lượng sản phẩm: " + e.getMessage(),
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    public void fillTableDHNV2() {
        Object selected = cboDH.getSelectedItem();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một năm để thống kê!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblDHNV2.getModel();
        model.setRowCount(0);

        String maNV = txtMaNV2.getText().trim();
        int nam = (Integer) selected;

        try {
            List<Object[]> list = dao.getDHNV(maNV, nam);
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Không tìm thấy dữ liệu cho " + (maNV.isEmpty() ? "bất kỳ nhân viên nào" : "nhân viên '" + maNV + "'")
                        + " trong năm " + nam + "!",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (Object[] row : list) {
                    model.addRow(new Object[]{
                        row[0], // Mã nhân viên
                        row[1], // Tên nhân viên
                        row[2] // Tổng hóa đơn
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Lỗi khi tải dữ liệu đơn hàng của nhân viên: " + e.getMessage(),
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    void fillTableDoanhThuThang() {
        Object selected = cboThang.getSelectedItem();
        if (selected == null) {
            return;
        }

        int thang = (Integer) selected;
        lblThangDT.setText("Tổng doanh thu của tháng:" + " " + String.valueOf(thang));

        DefaultTableModel model = (DefaultTableModel) tblDoanhThuThang.getModel();
        model.setRowCount(0);

        List<Object[]> list = dao.getDTTT(thang);
        for (Object[] row : list) {
            model.addRow(row);
        }

        if (tblDoanhThuThang.getRowCount() > 0) {
            double togDt = Double.parseDouble(tblDoanhThuThang.getValueAt(0, 1).toString());
            lblTogThang.setText((int) togDt + " VND");
        }
    }

}
